on:
  workflow_dispatch:
  push:
    branches:
      - main

name: fox32os Unstable

jobs:
  fox32os-unstable-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download latest fox32asm artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: fox32-arch/fox32asm
          workflow: fox32asm-unstable.yml
          workflow_conclusion: success

      - name: Download latest fox32rom artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: fox32-arch/fox32rom
          workflow: fox32rom-unstable.yml
          workflow_conclusion: success

      - name: Download latest tools artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: fox32-arch/tools
          workflow: tools-unstable-linux.yml
          workflow_conclusion: success

      - name: Install lua5.4
        run: |
          sudo apt update
          sudo apt install -y lua5.4 unzip

      - name: Build
        run: |
          mkdir ../fox32rom
          cp fox32rom.def/fox32rom.def ../fox32rom/
          unzip fox32asm-linux-x86_64/fox32asm-*-x86_64-linux.zip
          chmod +x ./fox32asm gfx2inc/gfx2inc
          make FOX32ASM=$(pwd)/fox32asm GFX2INC=$(pwd)/gfx2inc/gfx2inc

      - name: Upload fox32os.img
        uses: actions/upload-artifact@v4
        with:
          name: fox32os.img
          path: fox32os.img

      #- name: Upload romdisk.img
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: romdisk.img
      #    path: romdisk.img

      - name: Upload fox32os.def
        uses: actions/upload-artifact@v4
        with:
          name: fox32os.def
          path: fox32os.def
